# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title   : Thinger.io Plugins
tagline : Discover and Deploy Powerful Plugins at thinger.io Marketplace
email   : plugins@thinger.io
description: >- # this means to ignore newlines until "baseurl:"
  Unlock IoT innovation at Thinger.io Plugins Marketplace. Elevate your projects with powerful plugins, stay updated with the latest releases, and seamlessly integrate new capabilities into your Thinger.io platform. Join us and embark on a data-driven IoT journey today.
url     : "https://plugins.thinger.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl : "" # the subpath of your site, e.g. /blog
repository: thinger-io/plugins
author: thinger.io
#twitter_username: thinger_io
#github_username:  thinger-io

# Where things are
#includes_dir: .
collections:
  announcements:
defaults:
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: "/**/gui/**/*.html"
    values:
      sitemap: false

# Handling Reading
exclude : ["Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
include : ["_docs", "."]

# Serving
show_dir_listing : false

# Build settings
#theme: minima
theme: just-the-docs
permalink: pretty
logo: "/_docs/assets/thinger_logo_black.png"
favicon_ico: "/_docs/assets/io_icon.ico"
aux_links:
  Homepage:
    - 'https://thinger.io'
  Docs:
    - 'https://docs.thinger.io'
  GitHub:
    - 'https://github.com/thinger-io/plugins/'
footer_content : "Copyright &copy; 2016-2023 Thinger.io."

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

### --- Customization
# Color scheme supports "light" (default) and "dark"
color_scheme: thinger_light




### -- END Customization

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Feed settings
feed:
  posts_limit: 20
  collections:
    announcements:
      categories:
        - vscode
    posts:
      path: "404.html"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
